# Generated by Django 5.0.2 on 2024-02-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_order_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="merchant_id",
            new_name="payment_intent",
        ),
    ]
