# Generated by Django 5.0.2 on 2024-02-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_rename_merchant_id_order_payment_intent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_intent",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
