# Generated by Django 5.0.2 on 2024-02-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_vendor",
            field=models.BooleanField(default=False),
        ),
    ]
